### ISSUE TITLE
Request to add a benchmark of fasthttp based websocket 

### ISSUE THREAD

**Issue by WeiquanWa** [lesismal/go-websocket-benchmark#4]

**Comment by lesismal** [comment]
Yes, will add more frameworks.

I'm currently working on perfecting the framework infrastructure, and maybe investing in more frameworks after this.

And will always appreciate PR!

**Comment by lesismal** [comment]
BTW, whichever websocket framework we use, it will do Hijack and after that, fasthttp would never manage the conn again, the performance and cpu/mem/... usage will totally be controlled by the websocket framework itself.

I gonna add this fasthttp/websocket:
https://github.com/fasthttp/websocket

The performance and cpu/mem/... usage may not be much different from gorilla/websocket, because it's a fork from the latter as its README said:
```text
This project is a fork of the latest version of [gorilla/websocket](https://github.com/gorilla/websocket) that continues its development independently.
```

**Comment by lesismal** [comment]
`fasthttp/websocket` added:
https://github.com/lesismal/go-websocket-benchmark/blob/main/frameworks/fasthttp_ws/server.go
