### ISSUE TITLE
Add gnet please

### ISSUE THREAD

**Issue by trungdlp-wolffun** [lesismal/go-websocket-benchmark#42]
https://github.com/panjf2000/gnet
https://github.com/gnet-io/gnet-examples/tree/v2/websocket

**Comment by lesismal** [comment]
Thank you for your attention to this repo!

As I know, gobwas/ws's upgrader depends on blocking mod  reader:
https://github.com/gobwas/ws/blob/master/server.go#L447

But gnet's conn is non-blocking, so, I think the `readLine` maybe fail when there are not enough bytes for this conn. Fot TCP conn, its streaming bytes doesn't promise every ws frame's bytes arrive together, which means there may be half-packet ws frame. That may makes the readLine failed. And also the wsutil.ReadMessage has the same problem, it may fail too.
There have been some similar issues in gobwas/ws's issue list, and I have pointed out the reason for the problems in the issues before. For more information, you can search me in gobwas/ws's issue list.

Based on these factors, I think both gobwas/ws and the gnet ws example based on gobwas/ws are not production-suitable solutions.

We should accept full-featured and production-suitable solutions only. So, gnet's ws example is not suitable for now.

If there is a new implementation that can solve the problems, pr will be welcomed.

**Comment by lesismal** [comment]
BTW, about performance, gnet's official benchmark may make some misunderstanding, because gnet has different read buffer config, which is unfair to std net.

Here's also a benchmark repo for TCP:
https://github.com/lesismal/go-net-benchmark
Here are some results I got in my env:
https://github.com/lesismal/go-net-benchmark/issues/1

But, rather than claiming a higher performance than std and any other frameworks, I would suggest you to run the benchmark code yourself in your env, and better check the configurations of different frameworks to keep fair between them.

**Comment by lesismal** [comment]
I found there is gnet-benchmark in nbio's users, but I can't find nbio examples in gnet-benchmark now. Maybe some users have compared nbio with some other frameworks in gnet-benchmark repo, but remove nbio for some reason, interesting......

<img width="1474" alt="image" src="https://github.com/lesismal/go-websocket-benchmark/assets/40462947/71bdfa03-8c93-4046-8972-9050906468f1">

**Comment by lesismal** [comment]
gnet official doesn't support TLS/HTTP/Websocket, while nbio does, welcome to try nbio~ :smile:
